### PR TITLE
ci: investigations

### PR DESCRIPTION
**Pull request by jorgepiloto**
Continuation of #1400 since it looks like the generated pages are missing the Meilisearch data.

### CODE REVIEW

**Comment by jorgepiloto** [comment]
It looks like the environment variable is being passed. However, the search bar only shows up in this page: https://dpf.docs.pyansys.com/version/stable/search.html

**Comment by jorgepiloto** [comment]
I am suspecting now about the Sphinx version.

**Comment by Revathyvenugopal162** [comment]
docs build will only trigger if the PR is not draft, so changing the PR from draft to test

**Comment by Revathyvenugopal162** [comment]
i reverted the sphinx version back to 5.3.0 and the ci passes. we need to
 investigate further to see the issue with the sphinx upgraded version.

**Comment by Revathyvenugopal162** [comment]
The build failed with Sphinx 7.2.6, prompting me to switch to version 7.1.0. The underlying issue with the search bar was that the 'pydata sphinx theme' was mistakenly included as an extension in the 'conf.py' file, causing it to override the desired 'ansys sphinx theme' and consequently affecting the search functionality. Now the search is working , please see the video attached took with artifacts.

https://github.com/ansys/pydpf-core/assets/104772255/e5982778-b961-48f7-86c6-a4eb4ffee87b
@PProfizi and @jorgepiloto thank you for helping on fixing this issue. if you agree we can revert the unwanted changes on this PR and merge this PR.

**Review by Revathyvenugopal162 — APPROVED** [review]

**Pull request merged**
