### PR TITLE
Revert "Update the iso_contours example using iso_surfaces operator"

### PR DESCRIPTION
**Pull request by MichaelNale**
Reverts ansys/pydpf-core#1164

### CODE REVIEW

**Comment by PProfizi** [comment]
Necessary due to incompatibility between this new version of the example and DPF 2024.1.pre0.
This PR should be revert itself once ansys-dpf-core for DPF 2024.1.pre1 is under preparation.

**Comment by rafacanton** [comment]
@PProfizi I don't understand. Wouldn't it be better to just mark it as limited to versions >=7.1?

**Comment by PProfizi** [comment]
@rafacanton sadly no, since it already appears in the doc in its older version, we can't just bump the required version to a DPF verion that is not released yet. The point is we don't want to it disappear upon the release of a new ansys-dpf-core, which is what would happen if we mark it as requiring a higher DPF version than what is currently available.

**Comment by PProfizi** [comment]
When generating the doc, we filter out the examples that require a DPF version superior to what is being used to generate the doc.

**Pull request merged**
