### PR TITLE
Update generated code for DPF 242_eramosfe on master

### PR DESCRIPTION
**Pull request by PProfizi**
An update of generated code has been triggered either manually or by an update in the dpf-standalone repository.

### CODE REVIEW

**Comment by rafacanton** [comment]
@PProfizi, @anseramosfe I think we have a sync issue. The server has not been updated yet (the 2 PRs by Edu are not still merged), but somehow the automatic update of the client has been triggered. How is this possible?

**Comment by rafacanton** [comment]
> @PProfizi, @anseramosfe I think we have a sync issue. The server has not been updated yet (the 2 PRs by Edu are not still merged), but somehow the automatic update of the client has been triggered. How is this possible?

OK, I just saw the Closed PRs :). @PProfizi do they fix the issue?

**Comment by PProfizi** [comment]
> > @PProfizi, @anseramosfe I think we have a sync issue. The server has not been updated yet (the 2 PRs by Edu are not still merged), but somehow the automatic update of the client has been triggered. How is this possible?
> 
> OK, I just saw the Closed PRs :). @PProfizi do they fix the issue?

Hey @rafacanton , yeah I just had to fix a problem where this CI was not picking the right standalone branch. Now it does.

**Comment by rafacanton** [comment]
> > > @PProfizi, @anseramosfe I think we have a sync issue. The server has not been updated yet (the 2 PRs by Edu are not still merged), but somehow the automatic update of the client has been triggered. How is this possible?
> > 
> > 
> > OK, I just saw the Closed PRs :). @PProfizi do they fix the issue?
> 
> Hey @rafacanton , yeah I just had to fix a problem where this CI was not picking the right standalone branch. Now it does.

Then I guess that @anseramosfe needs to redo the process (close and reopen the PRs in dpf_standalone to run the pydpf-core CI, then merge these and then that would trigger this update generated code)

**Comment by anseramosfe** [comment]
> > > > @PProfizi, @anseramosfe I think we have a sync issue. The server has not been updated yet (the 2 PRs by Edu are not still merged), but somehow the automatic update of the client has been triggered. How is this possible?
> > > 
> > > 
> > > OK, I just saw the Closed PRs :). @PProfizi do they fix the issue?
> > 
> > 
> > Hey @rafacanton , yeah I just had to fix a problem where this CI was not picking the right standalone branch. Now it does.
> 
> Then I guess that @anseramosfe needs to redo the process (close and reopen the PRs in dpf_standalone to run the pydpf-core CI, then merge these and then that would trigger this update generated code)

Yes, I will do that. It is desirable to make sure the whole process work end-to-end too I think.

**Pull request closed without merging**
