### PR TITLE
Enable parallel_projection as a kwarg

### LINKED ISSUE #1532: Please add option for parallel views
### Description of the feature

At present, models can only be displayed in perspective view in ansys-dpf, but in most cases parallel view is better (because it prevents the model from being deformed due to viewing). There is already a parameter "parallel_projection" in the pyvista.plot() function, but it does not work if the parameter is specified as True in ansys-dpf.

### Steps for implementing the feature

_No response_

### Useful links and references

_No response_

### PR DESCRIPTION
**Pull request by PProfizi**
Closes #1532

### CODE REVIEW

**Review by BClappe — APPROVED** [review]

**Review by ZanePC — COMMENTED** [review]
Thank you, it's working!

**Comment by ZanePC** [comment]
Sorry, it's me again. A new problem has arisen. In the same camera perspective (cpos), the field of view in parallel views is much smaller than that in perspective views, so the zoom option in pyvista. plot() is needed to adjust the field of view. Although that can be manually adjusted in interactive mode (interactive=True), it is impossible to adjust each image when saving screenshots in batch mode. I tried to modify the source code of dpf, but failed.

**Comment by ZanePC** [comment]
Thanks to your prompt, I succeeded! I have added code in the following two places in dpf/core/printer.py, hoping to add it to future versions (if this is the most elegant way to implement it).

Code 1
image

Code 2
image

**Comment by ZanePC** [comment]
Sure, I'm glad I could offer you this little bit of help. Thank you very much for your excellent work!

**Comment by ZanePC** [comment]
Hi PProfizi, I'm here to provide feedback again. I'm sorry I didn't finish all the related issues at once. The new issue is that when using the DpfPlotter class for plotting, "parallel_projection=True" will fail. So I moved the code you wrote to the vicinity of the "zoom" code mentioned last time, and the modified code is as follows:

Code 1
image

Code 2
image

Code 3
image

**It should be noted that the code snippet for "parallel_projection" must come before "zoom", otherwise "zoom" will not work**

After my testing, "parallel_projection" and "zoom" can all work in the following three plotting methods: 
1. Class Model, function model.metadata.meshed_region.plot(); 
2. Class DpfPlotter, function show_figure(); 
3. Class Plotter, function plot_contour().

**Comment by ZanePC** [comment]
> @ZanePC thanks for that, I'll make a PR proposing these changes if that's OK with you. I'll also update the plotting examples and the docstrings.

Hello PProfizi,

In the new version of dpf, although parallel view can now be activated, "zoom" functionality is still not available. The code modifications I mentioned earlier can resolve this issue ([link attached](https://github.com/ansys/pydpf-core/pull/1535#issuecomment-2094669294)). I hope these changes can be incorporated into the next version. Thank you very much!

Best regards

**Pull request merged**
